version: '2'
services:
  ferdium:
    image: lscr.io/linuxserver/ferdium:latest
    container_name: ferdium
    security_opt:
      - seccomp:unconfined #optional mais recommandé
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /var/lib/docker/volumes/ferdium/config:/config
    ports:
      - 3500:3000
      - 3501:3001
    shm_size: "1gb"
    restart: unless-stopped
