version: '2'

services:
  roundcubemail:
    image: roundcube/roundcubemail:latest
    container_name: roundcubemail
#    restart: unless-stopped
    volumes:
      - /var/lib/docker/volumes/roundcube/www:/var/www/html
      - /var/lib/docker/volumes/roundcube/db:/var/roundcube/db
      - /var/lib/docker/volumes/roundcube/config:/var/www/config
    ports:
      - 9002:80
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_SKIN=elastic
