version: "2"
services:
  ferdium-server:
    image: ferdium/ferdium-server:latest
    container_name: ferdium-server
    environment:
      - NODE_ENV=xSCMSx
      - APP_URL=ferdium.xscmsx.fr
      - DB_CONNECTION=sqlite
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=Prize-Deputy-Unchain2
      - DB_DATABASE=ferdium
      - DB_SSL=false
      - MAIL_CONNECTION=smtp
      - SMTP_HOST=mailcowdockerized-postfix-mailcow-1
      - SMTP_PORT=25
      - MAIL_SSL=True
      - MAIL_USERNAME=marcmorin@xscmsx.fr
      - MAIL_PASSWORD=Suffrage2-Xerox-Tank
      - MAIL_SENDER=marcmorin@xscmsx.fr
      - IS_CREATION_ENABLED=true
      - IS_DASHBOARD_ENABLED=true
      - IS_REGISTRATION_ENABLED=true
      - CONNECT_WITH_FRANZ=false
      - DATA_DIR=/data
      - JWT_USE_PEM=true
    volumes:
      - /var/lib/docker/volumes/ferdium/data:/data
      - /var/lib/docker/volumes/ferdium/recipes:/app/build/recipes
    ports:
      - 3333:3333
    restart: unless-stopped
volumes:
  ferdium-recipes-vol:
  ferdium-database-vol:
