version: '2'

services:
  roundcubedb:
    image: mysql:latest
    container_name: roundcubedb
#    restart: unless-stopped
    volumes:
      - /var/lib/docker/volumes/roundcube/db/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=roundcube-mysql-pw
      - MYSQL_DATABASE=roundcubemail

  roundcubemail:
    image: roundcube/roundcubemail:latest
    container_name: roundcubemail
#    restart: unless-stopped
    depends_on:
      - roundcubedb
    links:
      - roundcubedb
    volumes:
      - var/lib/docker/volumes/roundcube/www:/var/www/html
    ports:
      - 9001:80
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=roundcubedb
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcube-mysql-pw
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://mail.infomaniak.com
      - ROUNDCUBEMAIL_SMTP_SERVER=tls:/ssl0.ovh.net
