version: '3.7'
services:
  ferdium:
    image: lscr.io/linuxserver/ferdium:latest
    container_name: ferdium
    security_opt:
      - seccomp:unconfined #optional mais recommandé
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /var/lib/docker/volumes/ferdium/config:/config
    ports:
      - 3500:3000
      - 3501:3001
    shm_size: "1gb"
    restart: unless-stopped
services:
  ferdium-server:
    image: ferdium/ferdium-server:latest
    container_name: ferdium-server
    environment:
      - NODE_ENV=production
      - APP_URL=https://ferdium.xscmsx.fr
      - DB_CONNECTION=sqlite
      - DATA_DIR=/data
      - IS_CREATION_ENABLED=true
      - IS_DASHBOARD_ENABLED=true
      - IS_REGISTRATION_ENABLED=true
      - CONNECT_WITH_FRANZ=false
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /var/lib/docker/volumes/ferdium/data:/data
      - ferdium-recipes-vol:/app/recipes
    ports:
      - 3333:3333
    restart: unless-stopped

volumes:
  ferdium-recipes-vol:/var/lib/docker/volumes/ferdium/recipes
