version: '3.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - /var/lib/docker/volumes/nextcloud/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 9003:80
    volumes:
      - /var/lib/docker/volumes/nextcloud/nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
    depends_on:
      - db

  cron:
    image: nextcloud
    restart: always
    volumes:
      - /var/lib/docker/volumes/nextcloud/nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
