version: '3.8'

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    environment:
    MYSQL_ROOT_PASSWORD: root_password
    MYSQL_DATABASE: nextcloud
    MYSQL_USER: nextcloud_user
    MYSQL_PASSWORD: nextcloud_password
    volumes:
    - /var/lib/docker/volumes/nextcloud/db:/var/lib/mysql

  app:
    image: nextcloud
    restart: always
    ports:
    - 8080:80
    environment:
    MYSQL_HOST: db
    MYSQL_DATABASE: nextcloud
    MYSQL_USER: nextcloud_user
    MYSQL_PASSWORD: nextcloud_password
    depends_on:
    - db
    volumes:
    - /var/lib/docker/volumes/nextcloud/nextcloud:/var/www/html
